version: "3.8"

volumes:
  mysql_dbdata2:

services:
  mysql_database:
    container_name: mysql
    image: mysql:5.7
    env_file: .env
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_dbdata2:/var/lib/mysql


  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

  app:
    container_name: crud-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_database
    ports:
      - "3013:3013"
      - "5555:5555"
    volumes:
      - .:/vln/app

